### ISSUE TITLE
[Feature] Run rules that don't care about individual files

### ISSUE THREAD

**Issue by folz** [discord/endanger#1]
Hi, thanks again for writing Endanger! We've been using it at Nextdoor for about a week now, and it's been great.

I think the idea of having a self-contained Rule to organize my effects is key. I have some things I want to express as Rules that don't care about individual files.

Examples:
* If a PR matches a Jira identifier regex, link the ticket with `message`.
* If a PR has 'wip' or 'donotmerge' labels, `warn` to remove them before merging (or `fail` until they are gone).

I know I can currently do these at the top level of the Dangerfile directly, but I really really like being able to organize the effects of my Dangerfile into Rules and understand at a glance what runs and when. It also would make it easier to package Rules to share across multiple repositories - I can think of a number of teams who could use a Jira identifier message Rule.

As I understand it, `run` skips executing a rule if it has no matching files: 
https://github.com/discord/endanger/blob/77486696244f67647bb099f1cd4b2338a4679c33/src/run.ts#L47

Would you be open to a PR that allows configuring Rules to run without declaring files to run against?

**Comment by jamiebuilds** [comment]
You can probably get by just by setting:

```js
files: ["**"]
```

Alternatively, what about a separate `commits` config that allows it to trigger based on regex?

```js
import { Rule } from "endanger"

let TICKET_REGEX = /\b(JIRA-\d+)\b/

export default function myFirstRule() {
  return new Rule({
    commits: [TICKET_REGEX],
    messages: {
      jiraLink: `
        [View linked ticket {ticket} on JIRA](https://jira.intranet.corp/{ticket})
      `,
    },
    async run(files, context) {
      for (let commit of context.git.commits) {
        let match = commit.message.match(TICKET_REGEX)
        if (match) {
          context.message("jiraLink", {}, {
            ticket: match[1],
          })
        }
      }
    },
  })
}
```

Already working on the `context.git.commits` bit here: https://github.com/discord/endanger/commit/baaea243f406824a283de35672328f908bffaa7d

**Comment by folz** [comment]
Yeah, I think `files: **` will work for me for now.

A `commits` filter sounds good and would address my immediate use case. Looking forward to what you come up with!

Some spitballing follows that might be too over-engineered but I wanted to suggest.

I can think of a couple other possibilities:

* `labels: ['...']`- if a label is applied to the PR (WIP or DONOTMERGE rules)
* `function(context) => boolean` - arbitrary filter function

Maybe separating it out into a Target class could help prevent overloading the Rule top-level API? 
```js
return new Rule({
  target: new Target({
    files: [],
    commits: [],
    filter: () => boolean
  }),
  ...
});
```
Maybe we would want to enforce only one of those keys can be passed (otherwise would they be AND'd or OR'd?), or have a FilesTarget, CommitsTarget, FilterTarget.

This could allow consumers of a shared Rule to pass in a Target() to the function that returns the rule,

```js
function messageJira(target) {
  return new Rule({
    target,
    messages: // ...
    run: // ...
  });
}

run(
  messageJira(new Target({
    filter: (context) =>
      my_team_members.includes(context.pr.author)
  }))
)
```

**Comment by jamiebuilds** [comment]
I think that would be a bit of overkill for what is required here.

The idea behind the `files: []` array is that it is meant to force you to declare all the files that your rule actually cares about and if any one of them were touched in some way the entire rule fires.

So I'm okay deciding that the behavior of multiple configured "targets" should be that if _any_ of them match the rule fires.

This is what I'm currently thinking of:

```ts
export default function myRule() {
  return new Rule({
    // possibly nest these so they are clearer?
    match: {
      files: ["glob/**"],
      commits: [/regex/],
      labels: [/regex/, "string"],
    },

    // might also change the `run()` arguments so you can use destructuring like this:
    async run({ files, commits, labels, pullRequest, context }) {
      // ...
    },
  })
}
```

I'd like to make `commits` / `labels` / etc only return values that you (potentially) matched against so we don't run into the problem of having devs think their rule is going to run when it's not actually being matched. For example:

```ts
export default function myDependabotRule() {
  return new Rule({
    match: {
      // ...
    },
    async run({ files, commits, labels, context }) {
      if (labels.has("dependencies")) {
        checkSomething()
      }
    },
  })
}
```

This rule will never actually run because it has nothing in `match: {}` but the developer might expect it to trigger on PRs that have the `"dependencies"` label.

> This could allow consumers of a shared Rule to pass in a Target() to the function that returns the rule,

I think I'd rather rules curate that a little bit better. Your `messageJira` rule could be written:

```ts
function messageJira({ authors }) {
  return new Rule({
    match: {
      author: [...authors],
    },
  });
}

run(
  messageJira({
    authors: my_team_members
  })
)
```

**Comment by folz** [comment]
Appreciate the explanation. The way you've extended "matching on what you care about" to more than files makes sense to me, and returning matched values gets rid of everything I thought I'd need a `filter: () => boolean` for since I can put that logic in the `run()` itself. +1 as well to changing run to destructure from the arg. Thank you!
